version: "3.9"
services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sample_dev
    ports:
      - "5432:5432"